# Site settings
title: Alwayswithme's Blog
email: phx13ye@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Doing all I can. To be a better man.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alwayswithme.github.io" # the base hostname & protocol for your site
so_username: phoenixYip
github_username:  Alwayswithme

# Build settings
markdown: kramdown
highlighter: pygments
# permalink: /:categories/:short_year/:month/:day/:title/